[[section-architecture-overview]]
=== Architecture Overview

[plantuml, component-diagram, svg, align="center", width=50%, scaledwidth=50%]
....
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND
skinparam linetype polyline 

title **Architecture Overview**

Person(devOps, "Devops", "Devops personnel accessing logs")

System_Boundary(cf, "Cloud Foundry"){
    Container(loggregator, "Loggregator", "CF Infrastructure", "Loggregator Log Aggregator")
    Boundary(cfappspace, "CF Applications"){
        Container(cfapp, "CF Application", "cf app", "CloudFoundry Application logging to stdout")
        Container_Boundary(logging, "logproxy"){
            
            Component(api, "Syslog REST API", "golang", "REST Endpoint consuming Syslog messages")
            Component(transform, "Transformer", "golang", "Parse and Transform Syslog messages to internal representation")

            Component(worker, "Worker", "golang", "RabbitMQ Worker to batch and send messages to HSDP Logging")
            
            Rel_R(api, transform, "uses")
        }
    }

    Rel(loggregator, cfapp, "collect", "cf-internal-api")
    Rel(loggregator, api, "stream", "http/api+syslog")    
}

System_Ext(rmq, "RabbitMQ Server", "RabbitMQ Server for storing logproxy messages")
System_Ext(hsdp_logservice, "HSDP Log Ingestor", "HSDP Foundation logging service REST API")

System_Ext(hsdp_kibana, "HSDP Hosted Kibana", "Hosted ELK cluster by HSDP")


Rel(transform, rmq, "publish", "AMQP")
Rel(rmq, worker, "consume", "AMQP")

Rel(worker, hsdp_logservice, "uses", "HTTP/api+hsdp.logging")
Rel_R(hsdp_logservice, hsdp_kibana, "uses", "hsdp-internal")

Rel(devOps, hsdp_kibana, "uses", "http/browser")

....
