name: docker
 
on:
 push:
   branches: [main]
 
jobs:
 docker:
   runs-on: ubuntu-latest
   steps:
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     -
       name: Login to DockerHub
       uses: docker/login-action@v3
       if: github.ref == 'refs/heads/main'
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     -
       name: Login to HSDP Docker registry
       uses: docker/login-action@v3
       if: github.ref == 'refs/heads/main'
       with:
         registry: docker.na1.hsdp.io
         username: ${{ secrets.HSDP_DOCKER_USERNAME }}
         password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
     -
       uses: actions/checkout@v5
     -
       name: Build logproxy
       uses: docker/build-push-action@v6
       with:
         context: ./
         file: ./Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         provenance: false
         tags: philipssoftware/logproxy:latest,docker.na1.hsdp.io/philipssoftware/logproxy:latest
