name: CI-Build-Package

on:
  push:
    branches:
      - master
      - develop
      - release/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker build --tag 'logproxy-builder:latest' --file Dockerfile.build .
          docker run --rm -v `pwd`:/src logproxy-builder:latest
